# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-10-10 15:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Friend',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('puid', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=20)),
                ('nick_name', models.CharField(max_length=50)),
                ('avatar', models.CharField(max_length=200)),
                ('date_time', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
